server:
  port: 9999
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/to-do-tracker-app?createDatabaseIfNotExist=true
    username: root
    password: abc
    driver: com.mysql.cj.jdbc,Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: API-TO-DO-AUTHENTICATION
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
