server:
  port: 7777
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: dummycapstonproject@gmail.com
    password: pnbkjovrgrruiemv
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
          auth: true
          #required: true

  application:
    name: API-TO-DO-EMAIL
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
